### PR TITLE
Docker compose files for CI

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by adam-fowler** [comment]
Is there anything that can be done to move this forward?

**Comment by tomerd** [comment]
@adam-fowler I think you can merge this, the nightly issue does not seem to be related to this repo and hopefully will be solved at the compiler level soon. in any case the nightly check is not blocking

**Pull request merged**
